DATAFRAME
dataframe is basically the combination of the Series.

In [2]:
import numpy as np
import pandas as pd

Creating a DataFrame

In [3]:
#using Dictionary
data = {
    'Name' : ['John','Anna','Peter','Linda'],
    'Age' : [28,34,29,42],
    'City' : ['New York','Paris','Berlin','London'],
    'Salary' : [65000,70000,62000,85000,]
}
df = pd.DataFrame(data)

In [4]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
#using the list
data_list = [
    ['John',28,'New York',65000],
    ['Anna',34,'Paris',70000],
    ['Peter',29,'Berlin',62000],
    ['Linda',42,'London',85000],
]

In [6]:
dfl = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
dfl2 = pd.DataFrame(data_list,columns = columns)

In [7]:
dfl

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [8]:
dfl2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Selection and indexing of columns

In [10]:
#in data frames column names matter and not he indexing. to target columns we have to write the column name
dfl2['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: object

In [11]:
#for targeting multiple columns we pass a list of list
dfl2[['Name','City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

Creating a new column

In [12]:
dfl2['Designation'] = ['Doctor','Engineer','Doctor','Engineer']

In [13]:
dfl2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

dfl2

Removing Columns

In [14]:
dfl2.drop('Designation',axis=1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [15]:
#for removing multiple(but remember that this only creates the view and does not remove it from teh orginal dataframe.for slving this using ",inplace=True")

dfl2.drop(['Designation','Age'],axis=1)

    Name      City  Salary
0   John  New York   65000
1   Anna     Paris   70000
2  Peter    Berlin   62000
3  Linda    London   85000

In [16]:
#similarly for removing the  row change axis =1 to axis =0 or don't give the value of axis
dfl2.drop(0)

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000    Engineer
2  Peter   29  Berlin   62000      Doctor
3  Linda   42  London   85000    Engineer

Selecting Rows

In [17]:
dfl2.loc[0]

Name               John
Age                  28
City           New York
Salary            65000
Designation      Doctor
Name: 0, dtype: object

In [19]:
dfl2.loc[[0,1]]

   Name  Age      City  Salary Designation
0  John   28  New York   65000      Doctor
1  Anna   34     Paris   70000    Engineer

In [21]:
dfl2.iloc[3] #uses index

Name              Linda
Age                  42
City             London
Salary            85000
Designation    Engineer
Name: 3, dtype: object

Selecting Subsets of Rows and Columns

In [22]:
dfl2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

Conditional Selection

In [23]:
dfl2[dfl2["Age"]>30]

    Name  Age    City  Salary Designation
1   Anna   34   Paris   70000    Engineer
3  Linda   42  London   85000    Engineer

In [24]:
dfl2[dfl2["Age"]>30 & dfl2["City"]=="Paris"]

TypeError: Cannot perform 'rand_' with a dtyped [object] array and scalar of type [bool]