In [1]:
import numpy as np
import pandas as pd

MISSING DATA

Finding missing Data

In [11]:
data = {
    'A': [1,2,np.nan,4,5],
    'B': [np.nan, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan ,np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)
df2 = pd.DataFrame(data)

In [4]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [6]:
#gives boolean mapping of whether a valus is null or not
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [7]:
#Gives columnwise sum of null values
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [9]:
# gives whether a column has null values or not
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

Removing missing data #this works on the row basis

In [10]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [12]:
# drops all rows with null values
df2.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [13]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [14]:
#thresh acts as a threshold value i.e, here all rows atleast 3 non null values won't be affected and all below 3 non null vlues will get deleted
df.dropna(thresh=3)

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

Filling the missing data

In [16]:
#fill all null values with the given parameterized value in the fillna attribute
df.fillna(0)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [17]:
# to fill different values in place of each missing value in different columns
values = {'A':0,'B':100,'C':300,'D':400}
df.fillna(value = values)

     A      B      C      D
0  1.0  100.0    1.0    1.0
1  2.0    2.0    2.0  400.0
2  0.0    3.0    3.0  400.0
3  4.0    4.0  300.0  400.0
4  5.0    5.0  300.0    5.0

In [19]:
#to fill missing values with mean
df.fillna(df.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0